#!/usr/bin/bash

docker compose restart -t 1

if [ $? == 0 ] ; then
  docker compose up -d
fi

if [ $1 ] ; then
  docker exec -it $PROJECT_NAME-web bash -c "odoo -u $1 -d dev --db_user odoo --db_password odoo --stop-after-init"
fi

docker logs -f --tail 0 $PROJECT_NAME-web

