version: "3.8"
services:
  web:
    build: .
    image: ${PROJECT_NAME}:latest
    container_name: ${PROJECT_NAME}-web
    tty: true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - web:/var/lib/odoo
      - addons:/mnt/extra-addons
  db:
    image: postgres:13-alpine
    container_name: ${PROJECT_NAME}-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
        interval: 1s
        timeout: 1s
        retries: 3
volumes:
  web:
    driver: local
    name: ${PROJECT_NAME}-web
  db:
    driver: local
    name: ${PROJECT_NAME}-db
  addons:
    driver: local
    name: ${PROJECT_NAME}-addons
    driver_opts:
      type: none
      device: ${PWD}/addons
      o: bind

